import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import { notojp } from "./font";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, home }) {
  return (
    <html lang="en">
      <body
        className={`${notojp.className} flex flex-col w-[100%] m-auto m-full min-h-[100vh] font-light`}
      >
        {children}
        <div className="fixed w-full h-screen z-[-1]">
          <Image
            className="z-[-1] fixed"
            src="/Night.webp"
            fill={true}
            objectFit="cover"
            alt="wallpaper"
          />
          <div className="absolute inset-0 bg-slate-900/50 z-0 backdrop-blur"></div>
        </div>
      </body>
    </html>
  );
}
